---
# awsnodetemplate
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ebs-eks
    Name: "ebp-vpc-private-ap-northeast-2*" # TODO: template or dynamic gen
  securityGroupSelector:
    karpenter.sh/discovery: ebs-eks
    Name: ebp-eks-node # TODO: template or dynamic gen
  tags:
    karpenter.sh/discovery: ebs-eks
---
# provisioner
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  providerRef:
    name: default
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - t4g
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: "6"
      memory: 24Gi
